/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LYW' at '16/07/08 11:20' with Gradle 2.9
 *
 * @author LYW, @date 16/07/08 11:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
